project_id = "gtibewiiudfzqayummbl"

[functions.send-contact-email]
verify_jwt = false

[functions.get-visitor-location]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.decision-analysis]
verify_jwt = false

[functions.redteam-analysis]
verify_jwt = false

[functions.brand-profile-refine]
verify_jwt = false

[functions.brand-profile-generate]
verify_jwt = false

[functions.content-sprint-generate]
verify_jwt = false

[functions.engagement-analysis]
verify_jwt = false

[functions.prompt-engineer]
verify_jwt = false
